<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sauce Labs Bike Light</name>
   <tag></tag>
   <elementGuidId>6c4ea9b1-dd4b-46fc-bcbb-b2d7faec731b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-test=&quot;item-0-title-link&quot;] [data-test=&quot;inventory-item-name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-test = 'item-0-title-link']//*[@data-test = 'inventory-item-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-test=&quot;item-0-title-link&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b8e61234-6415-43d9-9932-9722c4099e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inventory_item_name</value>
      <webElementGuid>398d1df8-b172-4957-a91d-1916d239e715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>inventory-item-name</value>
      <webElementGuid>570c22d2-fde3-4f27-9063-cc24e65daa0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sauce Labs Bike Light</value>
      <webElementGuid>5faf6300-e098-4988-8448-9a93624dd730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ae02102a1a2504595ce4a5e521dcf802</value>
      <webElementGuid>c8a76bae-5772-486d-9c6e-e959b2f7cbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-test = 'item-0-title-link']//*[@data-test = 'inventory-item-name']</value>
      <webElementGuid>9ac12aaa-894d-4d8e-bfe2-048a653ebdba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-test = 'item-0-title-link']//*[@data-test = 'inventory-item-name']</value>
      <webElementGuid>81c45246-1932-48d7-bf05-c6005cbc1f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sauce Labs Bike Light' or . = 'Sauce Labs Bike Light')]</value>
      <webElementGuid>1af6926c-6a83-4316-b490-55e53fa1ce97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
